# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- gem install github_changelog_generator
script:
# - export CHANGELOG_GITHUB_TOKEN="62e3e57ab4ae4dc8e42fcaa23eb9be7675ce73cd"
- github_changelog_generator --token ba714ab76b27d584f807de7faf4a814f369fd6e1
- git status
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MasonryHidden.xcworkspace -scheme MasonryHidden-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
# - echo 'hello travis ci'

#指定分支，只有指定的分支提交时才会运行脚本
# branches:
#   only:
#     - master
# https://api.github.com/repos/SunnySunning/MasonryHidden/tags?per_page=100:
#                       /repos/:owner      /:repo/git/tags/:tag_sha

# curl -u SunnySunning:ba714ab76b27d584f807de7faf4a814f369fd6e1 https://api.github.com/user
