# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- gem install github_changelog_generator
script:
- github_changelog_generator --token 02c9a46f2511440882fb42037b5e864d508666ab
- git status
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MasonryHidden.xcworkspace -scheme MasonryHidden-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
# - echo 'hello travis ci'

#指定分支，只有指定的分支提交时才会运行脚本
# branches:
#   only:
#     - master
